WIP - Update scripts / environment

diff --git a/script/generate b/script/generate
--- a/script/generate
+++ b/script/generate
@@ -1,58 +1,57 @@
 #!/usr/bin/env bash
 
 function usage {
-    echo "generate [service] [ModuleName]"
+    echo "generate [service/repo] [ServiceName] [RepoName]"
     echo
 }
 
 function generate_service {
 
-    service=$1
-
-    # lower case service name
-    SERVICE_LC=$(echo "$service" | tr '[:upper:]' '[:lower:]')
-
-    echo "Generating service ${service}"
-
-    if [ -z "$service" ]; then
+    SERVICE_CC=$1
+    if [ -z "$SERVICE_CC" ]; then
         echo "Missing service name, cannot create new service"
         usage
         exit 1
     fi
 
+    # check service camel case
+    case ${SERVICE_CC:0:1} in
+    [A-Z])
+        echo "$SERVICE_CC looks good..."
+        ;;
+    *)
+        echo "$SERVICE_CC must be in CamelCase thanks!"
+        exit
+        ;;
+    esac
+
+    # lower case service name
+    SERVICE_LC=$(echo "$SERVICE_CC" | tr '[:upper:]' '[:lower:]')
+    SERVICE_UC=$(echo "$SERVICE_CC" | tr '[:lower:]' '[:upper:]')
+
+    echo "Generating service ${SERVICE_CC}"
+
     # create service directory
     mkdir ./service/${SERVICE_LC}
 
-    # build directories
-    mkdir ./service/${SERVICE_LC}/build
-    mkdir ./service/${SERVICE_LC}/build/ci
-    mkdir ./service/${SERVICE_LC}/build/package
+    # copy source
+    cp -R ./service/template/* ./service/${SERVICE_LC}
+    cp ./service/template/.env* ./service/${SERVICE_LC}/
 
-    # deploy directories
-    mkdir ./service/${SERVICE_LC}/deploy
-
-    # source directories
-    mkdir ./service/${SERVICE_LC}/cmd
-    mkdir ./service/${SERVICE_LC}/internal
-    mkdir ./service/${SERVICE_LC}/internal/cmd
-    mkdir ./service/${SERVICE_LC}/internal/model
-    mkdir ./service/${SERVICE_LC}/internal/repo
-    mkdir ./service/${SERVICE_LC}/internal/service
-
-    # copy template
-    SERVICE_FILENAME=./service/${SERVICE_LC}/${SERVICE_LC}.go
-    SERVICE_TEST_FILENAME=./internal/cmd/api/service/${SERVICE_LC}/${SERVICE_LC}_test.go
-
-    cp ./internal/cmd/api/service/template/template.go $SERVICE_FILENAME
-    cp ./internal/cmd/api/service/template/template_test.go $SERVICE_TEST_FILENAME
+    # rename specific files
+    mv ./service/${SERVICE_LC}/internal/repository/template ./service/${SERVICE_LC}/internal/repository/${SERVICE_LC}
+    mv ./service/${SERVICE_LC}/internal/repository/${SERVICE_LC}/template.go ./service/${SERVICE_LC}/internal/repository/${SERVICE_LC}/${SERVICE_LC}.go
+    mv ./service/${SERVICE_LC}/internal/repository/${SERVICE_LC}/test/template_test.go ./service/${SERVICE_LC}/internal/repository/${SERVICE_LC}/test/${SERVICE_LC}_test.go
 
     # replace template names
-    sed -i "" "s/template/$SERVICE_LC/g" $SERVICE_FILENAME
-    sed -i "" "s/template/$SERVICE_LC/g" $SERVICE_TEST_FILENAME
+    find ./service/${SERVICE_LC} -type f -exec perl -pi -e "s/template/${SERVICE_LC}/g" {} \;
+    find ./service/${SERVICE_LC} -type f -exec perl -pi -e "s/TEMPLATE/${SERVICE_UC}/g" {} \;
+    find ./service/${SERVICE_LC} -type f -exec perl -pi -e "s/Template/${SERVICE_CC}/g" {} \;
 
-    # replace template names
-    sed -i "" "s/Template/$service/g" $SERVICE_FILENAME
-    sed -i "" "s/Template/$service/g" $SERVICE_TEST_FILENAME
+    # check go module integrity
+    cd ./service/${SERVICE_LC}
+    go mod tidy
+    cd -
 }
 
 function generate_repo {
@@ -67,54 +66,20 @@ function generate_repo {
 
     echo "Generating repo ${REPO}"
 
-    # lower case repo name
-    REPO_LC=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
-
-    # create repo directory
-    mkdir ./internal/repo/${REPO_LC}
-
-    # copy template
-    REPO_FILENAME=./internal/repo/${REPO_LC}/${REPO_LC}.go
-    REPO_STATEMENTS_FILENAME=./internal/repo/${REPO_LC}/statements.go
-    REPO_RECORD_FILENAME=./internal/types/record/${REPO_LC}.go
-    REPO_TEST_FILENAME=./internal/repo/${REPO_LC}/${REPO_LC}_test.go
-
-    cp ./internal/repo/template/template.go $REPO_FILENAME
-    cp ./internal/repo/template/statements.go $REPO_STATEMENTS_FILENAME
-    cp ./internal/types/record/template.go $REPO_RECORD_FILENAME
-    cp ./internal/repo/template/template_test.go $REPO_TEST_FILENAME
-    cp ./internal/repo/template/mock.go $REPO_MOCK_FILENAME
-    cp ./internal/repo/template/mock_test.go $REPO_MOCK_TEST_FILENAME
-
-    echo "Repo filename            : ${REPO_FILENAME}"
-    echo "Repo statements filename : ${REPO_STATEMENTS_FILENAME}"
-    echo "Repo record filename     : ${REPO_RECORD_FILENAME}"
-    echo "Repo test filename       : ${REPO_TEST_FILENAME}"
-    echo "Repo mock filename       : ${REPO_MOCK_FILENAME}"
-    echo "Repo mock test filename  : ${REPO_MOCK_TEST_FILENAME}"
-
-    # replace template names
-    sed -i "" "s/template/$REPO_LC/g" $REPO_FILENAME
-    sed -i "" "s/template/$REPO_LC/g" $REPO_STATEMENTS_FILENAME
-    sed -i "" "s/template/$REPO_LC/g" $REPO_RECORD_FILENAME
-    sed -i "" "s/template/$REPO_LC/g" $REPO_TEST_FILENAME
-    sed -i "" "s/template/$REPO_LC/g" $REPO_MOCK_FILENAME
-    sed -i "" "s/template/$REPO_LC/g" $REPO_MOCK_TEST_FILENAME
-
-    # replace template names
-    sed -i "" "s/Template/$REPO/g" $REPO_FILENAME
-    sed -i "" "s/Template/$REPO/g" $REPO_STATEMENTS_FILENAME
-    sed -i "" "s/Template/$REPO/g" $REPO_RECORD_FILENAME
-    sed -i "" "s/Template/$REPO/g" $REPO_TEST_FILENAME
-    sed -i "" "s/Template/$REPO/g" $REPO_MOCK_FILENAME
-    sed -i "" "s/Template/$REPO/g" $REPO_MOCK_TEST_FILENAME
 }
 
 # command (repo, service)
 COMMAND=$1
+shift
 
 if [ -z "$COMMAND" ]; then
     echo "Missing command, cannot generate"
+    usage
+    exit 1
+fi
+
+if [[ "$1" == *'/'* ]]; then
+    echo "Generator does not support nesting directories, cannot generate"
     usage
     exit 1
 fi
@@ -127,14 +92,17 @@ fi
 
 # generate repo
 if [ "$COMMAND" == "repo" ]; then
-    generate_repo $2
-    exit $?
+    generate_repo $1 $2
+    exit 1
 fi
 
 # generate service
 if [ "$COMMAND" == "service" ]; then
-    generate_service $2
-    exit $?
+    generate_service $1
+    exit 1
 fi
 
-
+echo "Unknown command ${COMMAND}. doing nothing!"
+echo
+usage
+exit 1
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -7,17 +7,28 @@ if [ $(command -v gvm) ]; then
     gvm use $GO_VERSION
 fi
 
+# copy development env
+cp .env.development .env
+
+# environment
+source ${BASH_SOURCE%/*}/environment || exit $?
+
+if ! [[ -n ${APP_DB_SERVICE} ]]; then
+    echo "=> (test-ci) Missing APP_DB_SERVICE"
+    exit 1
+fi
+
 # start database
-source ${BASH_SOURCE%/*}/start-database "docker" || exit $?
+source ${BASH_SOURCE%/*}/start-database || exit $?
 
 # migrate database
 source ${BASH_SOURCE%/*}/db-migrate-up || exit $?
 
 # test common
-source ${BASH_SOURCE%/*}/test-common "docker" || exit $?
+source ${BASH_SOURCE%/*}/test-common || exit $?
 
 # test service
-source ${BASH_SOURCE%/*}/test-service "docker" || exit $?
+source ${BASH_SOURCE%/*}/test-service || exit $?
 
 # stop services
-source ${BASH_SOURCE%/*}/stop-database "docker" || exit $?
+source ${BASH_SOURCE%/*}/stop-database || exit $?
diff --git a/script/test-ci b/script/test-ci
--- a/script/test-ci
+++ b/script/test-ci
@@ -6,14 +6,19 @@ cp .env.ci .env
 # environment
 source ${BASH_SOURCE%/*}/environment || exit $?
 
+if ! [[ -n ${APP_DB_SERVICE} ]]; then
+    echo "=> (test-ci) Missing APP_DB_SERVICE"
+    exit 1
+fi
+
 # start database
-source ${BASH_SOURCE%/*}/start-database "ci" || exit $?
+source ${BASH_SOURCE%/*}/start-database || exit $?
 
 # migrate database
 source ${BASH_SOURCE%/*}/db-migrate-up || exit $?
 
 # test common
-source ${BASH_SOURCE%/*}/test-common "ci" || exit $?
+source ${BASH_SOURCE%/*}/test-common || exit $?
 
 # test service
-source ${BASH_SOURCE%/*}/test-service "ci" || exit $?
+source ${BASH_SOURCE%/*}/test-service || exit $?
