Setup CI

diff --git a/script/test-local b/script/test-local
--- a/script/test-local
+++ b/script/test-local
@@ -1,5 +1,22 @@
 #!/usr/bin/env bash
 
+GO_VERSION=go1.13.3
+if [ $(command -v gvm) ]; then
+    source  ~/.gvm/scripts/gvm
+    echo "Using ${GO_VERSION}"
+    gvm use $GO_VERSION
+fi
+
+# environment
+cp .env.test .env
+status=0
+source ${BASH_SOURCE%/*}/environment || status=$?
+
+if [ $status -ne 0 ]; then
+    echo "Failed including environment" >&2
+    exit $status
+fi
+
 source ${BASH_SOURCE%/*}/start-services || status=$?
 
 if [ $status -ne 0 ]; then
