Cleanup CI

diff --git a/script/test-ci b/script/test-ci
--- a/script/test-ci
+++ b/script/test-ci
@@ -3,27 +3,15 @@
 # environment
 cp .env.test .env
 status=0
-source ${BASH_SOURCE%/*}/environment || status=$?
 
+source ${BASH_SOURCE%/*}/environment || status=$?
 if [ $status -ne 0 ]; then
     echo "Failed including environment" >&2
     exit $status
 fi
 
-# required for all environments
-MODULES=( \
-    'common/database' \
-    'common/env' \
-    'common/logger' \
-    'common/model' \
-    'common/repository' \
-    'common/service' \
-);
-
-for MODULE in ${MODULES[@]}; do
-
-    cd $MODULE
-    go test -v -count 1 . || exit $?
-    cd -
-
-done
+source ${BASH_SOURCE%/*}/test || status=$?
+if [ $status -ne 0 ]; then
+    echo "Failed test" >&2
+    exit $status
+fi
